"""Inline src/ and vendor/ into one self-contained HTML file.
Vendored libraries: ExcelJS, marked, JSZip (all MIT).

Writes docs/index.html (served by GitHub Pages) and docs/sheetwriter.html
(the same file under a name that is convenient to download and keep).

Usage:  python build.py
No dependencies beyond the standard library.
"""
import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent
SRC = ROOT / "src"
DOCS = ROOT / "docs"


def inline_css(m):
    p = (SRC / m.group(1)).resolve()
    return "<style>\n" + p.read_text(encoding="utf-8") + "\n</style>"


def inline_js(m):
    p = (SRC / m.group(1)).resolve()
    code = p.read_text(encoding="utf-8")
    code = re.sub(r"^//# sourceMappingURL=.*$", "", code, flags=re.M)
    code = code.replace("</script", "<\\/script")
    return f"<script>/* {p.name} */\n{code}\n</script>"


def inline_icon(m):
    svg = (SRC / m.group(1)).read_text(encoding="utf-8").strip()
    svg = svg.replace("#", "%23").replace('"', "'").replace("\n", "")
    return f'<link rel="icon" type="image/svg+xml" href="data:image/svg+xml,{svg}">'


def version():
    return re.search(r"version:\s*'([^']+)'", (SRC / "version.js").read_text(encoding="utf-8")).group(1)


def build():
    html = (SRC / "index.html").read_text(encoding="utf-8")
    html = re.sub(r'<link rel="stylesheet" href="([^"]+)">', inline_css, html)
    html = re.sub(r'<link rel="icon" type="image/svg\+xml" href="([^"]+)">', inline_icon, html)
    html = re.sub(r'<script src="([^"]+)"></script>', inline_js, html)
    html = html.replace("<!-- BUILD -->", f"<!-- SheetWriter {version()}. Single-file build: edit src/ and run build.py; do not edit this file. -->")
    DOCS.mkdir(exist_ok=True)
    for name in ("index.html", "sheetwriter.html"):
        out = DOCS / name
        with open(out, "w", encoding="utf-8", newline="\n") as f:  # LF on every platform, so CI can diff the build
            f.write(html)
        print(f"wrote {out} ({out.stat().st_size / 1024:.0f} KB)")
    with open(DOCS / "favicon.svg", "w", encoding="utf-8", newline="\n") as f:
        f.write((SRC / "favicon.svg").read_text(encoding="utf-8"))


if __name__ == "__main__":
    build()
